//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAccessLib.DataComponents
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatient
    {
        public int PatientId { get; set; }
        public string PatientName { get; set; }
        public string PatientAddress { get; set; }
        public int BillAmount { get; set; }
        public Nullable<int> DoctorID { get; set; }
    
        public virtual tblDoctor tblDoctor { get; set; }
        public virtual tblPatient tblPatient1 { get; set; }
        public virtual tblPatient tblPatient2 { get; set; }
    }
}
